spring:
  redis:
    database: 0
    #    host: 127.0.0.1
    #    port: 6379
    #    password:
    cluster:
      nodes:
        - 172.16.124.132:6379
    #    jedis:
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000

server:
  port: 8003
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

eureka:
  client:
    service-url:
      defaultZone: http://172.16.124.133:8761/eureka
    register-with-eureka: true
    fetch-registry: true

feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 1024
    response:
      enabled: true
